### ISSUE TITLE
npm run build doesn't work with Node.js v18.7.0

### ISSUE THREAD

**Issue by JaneGaid** [surveyjs/custom-widgets#311]
Node.js v18.7.0
The `npm run build` command ("build": "webpack --env buildType=prod") produces the following error:
```
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (D:\SurveyJS\Examples\custom-widgets\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (D:\SurveyJS\Examples\custom-widgets\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (D:\SurveyJS\Examples\custom-widgets\node_modules\webpack\lib\NormalModule.js:471:10)
    at D:\SurveyJS\Examples\custom-widgets\node_modules\webpack\lib\NormalModule.js:503:5
    at D:\SurveyJS\Examples\custom-widgets\node_modules\webpack\lib\NormalModule.js:358:12
    at D:\SurveyJS\Examples\custom-widgets\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (D:\SurveyJS\Examples\custom-widgets\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at Array.<anonymous> (D:\SurveyJS\Examples\custom-widgets\node_modules\loader-runner\lib\LoaderRunner.js:205:4)
    at Storage.finished (D:\SurveyJS\Examples\custom-widgets\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:55:16)
    at D:\SurveyJS\Examples\custom-widgets\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:91:9
    at D:\SurveyJS\Examples\custom-widgets\node_modules\graceful-fs\graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
```

**Comment by tsv2013** [comment]
Fixed, added build Github actions
